### ISSUE TITLE
不支持python3.4吗？

### ISSUE THREAD

**Issue by ziXiong** [zhangfisher/DjangoUeditor#42]

**Comment by iloveyo123u1** [comment]
求支持py3

**Comment by mo0feng** [comment]
确实不支持py3 报错

**Comment by twz915** [comment]
https://github.com/twz915/DjangoUeditor3
我在改进以兼容Python3，现在上传图片还有些问题

**Comment by wsqy** [comment]
已经做了django1.10的兼容 支持python3和python2双版本
https://github.com/wsqy/DjangoUeditor
